title: API rehab
description: A performance extravaganza for the API enthusiast
theme: just-the-docs

url: https://RiccardoGMoschetti.github.io/apirehab√π

logo: /docs/images/logo.png
favicon_ico: "/docs/images/favicon.ico"

aux_links:
  Template Repository: https://github.com/RiccardoGMoschetti/apirehab

callouts:
 important:
    title: 
    color: blue