title: API rehab
description: A performance extravaganza for the API enthusiast
theme: just-the-docs

url: https://RiccardoGMoschetti.github.io/apirehab

aux_links:
  Template Repository: https://github.com/RiccardoGMoschetti/apirehab

